language: ruby
dist: xenial
rvm: 2.7.2
bundler_args: --jobs=2
script:
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
