language: 
  - ruby
  - node_js
node_js:
  - 14
rvm:
- 2.7.2
bundler_args: --jobs=2
script:
  - bundle exec rake db:setup
  - NODE_ENV=test bundle exec rake webpacker:compile
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"
