language: ruby

rvm:
  - 2.7.2

addons:
  postgresql: "9.4"

before_script:
  - bundle exec rake db:create db:migrate RAILS_ENV=test

cache:
  bundler: true
  directories:
    - node_modules
  yarn: true

bundler_args: --jobs=2

install:
  - bundle install
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn

script:
  - bundle exec rails webpacker:compile
  - bundle exec rails 
  
services:
  - postgresql
addons:
  postgresql: "9.4"