language: 
  - ruby
  - node_js
cache:
  bundler: true
  directories:
    - node_modules
node_js:
  - 14
rvm:
- 2.7.2
bundler_args: --jobs=2
script:
  - npm install
  - npm audit fix
  - bundle exec rake db:setup
  - NODE_ENV=test bundle exec rake webpacker:compile
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"